# Generated by Django 2.1.2 on 2018-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
