# Generated by Django 2.1.2 on 2018-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181107_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='user',
        ),
        migrations.AddField(
            model_name='service',
            name='IBAN',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.DeleteModel(
            name='Boss',
        ),
    ]
