# Generated by Django 2.1.2 on 2018-11-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181107_1645'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='number_in_menu',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_by', to='users.Service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='orders.Drink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='users.Customer'),
        ),
    ]
