# Generated by Django 2.1.2 on 2018-10-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181016_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
