# Generated by Django 2.1.3 on 2018-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181107_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='week_day',
            field=models.IntegerField(default=-1),
        ),
    ]
