# Generated by Django 2.1.2 on 2018-10-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181017_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='number_in_menu',
            field=models.IntegerField(default=-1),
        ),
    ]
