# Generated by Django 2.1.3 on 2018-11-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_food_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img_url',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
