# Generated by Django 2.1.3 on 2018-11-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_food_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='drink',
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(null=True, related_name='drinks', to='orders.Drink'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(related_name='foods', to='orders.Food'),
        ),
    ]
