# Generated by Django 2.1.2 on 2018-10-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_food_number_in_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='drink',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
