# Generated by Django 2.1.3 on 2018-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181125_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(default=None, null=True, related_name='drinks', to='orders.Drink'),
        ),
    ]
