# Generated by Django 2.1.3 on 2018-11-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181125_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(default=None, related_name='drinks', to='orders.Drink'),
        ),
    ]
