# Generated by Django 2.1.3 on 2018-11-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181107_1645'),
        ('orders', '0007_auto_20181125_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ManyToManyField(default=None, related_name='drinks_in_chart', to='orders.Drink')),
                ('food', models.ManyToManyField(related_name='food_in_chart', to='orders.Food')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.Customer')),
            ],
        ),
    ]
