# Generated by Django 2.1.2 on 2018-11-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181107_1018'),
        ('orders', '0007_auto_20181106_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_by', to='users.Service'),
        ),
    ]
