# Generated by Django 2.1.3 on 2018-11-25 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='food',
            field=models.ManyToManyField(default=None, related_name='food_in_chart', to='orders.Food'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='users.Customer'),
        ),
    ]
