# Generated by Django 2.1.3 on 2018-12-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20181125_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
