# Generated by Django 2.1.3 on 2018-12-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_chart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, max_length=4),
        ),
    ]
